import React, { useState } from 'react';
import { Copy, Check, Database, Code, ShieldCheck, Cpu } from 'lucide-react';
import { generateSupabaseSqlSchema } from '../services/adService';

interface SchemaAndEmbedViewProps {
  tableName: string;
}

export const SchemaAndEmbedView: React.FC<SchemaAndEmbedViewProps> = ({
  tableName,
}) => {
  const [activeTab, setActiveTab] = useState<'sql' | 'vanilla' | 'react' | 'worker'>('sql');
  const [copied, setCopied] = useState(false);

  const sqlSchema = generateSupabaseSqlSchema(tableName);

  const vanillaJsEmbed = `<!-- 1. Place Container Where You Want Ad To Render -->
<div id="sponsored-product-slot" data-format="square" data-category="audio"></div>

<!-- 2. Async Lightweight Serverless Embed Script -->
<script>
(function() {
  const SLOT = document.getElementById('sponsored-product-slot');
  const FORMAT = SLOT.getAttribute('data-format') || 'square';
  const CATEGORY = SLOT.getAttribute('data-category') || 'global';
  
  // Fetch pre-compiled edge manifest generated by Compiler Webhook
  fetch(\`https://cdn.sponsorgrid.net/manifests/\${CATEGORY}/\${FORMAT}.json\`)
    .then(r => r.json())
    .then(ad => {
      SLOT.innerHTML = \`
        <div style="width:300px;background:#171717;border:1px solid #333;border-radius:12px;overflow:hidden;font-family:sans-serif;box-shadow:0 10px 15px -3px rgba(0,0,0,0.3);">
          <div style="position:relative;height:130px;background:#000;">
            <img src="\${ad.image_url}" alt="\${ad.title}" style="width:100%;height:100%;object-fit:cover;" />
            <span style="position:absolute;top:8px;left:8px;background:rgba(0,0,0,0.7);color:#fff;font-size:9px;padding:2px 6px;border-radius:4px;text-transform:uppercase;">Sponsored</span>
            \${ad.discount_badge ? \`<span style="position:absolute;top:8px;right:8px;background:#f59e0b;color:#000;font-size:10px;font-weight:bold;padding:2px 6px;border-radius:4px;">\${ad.discount_badge}</span>\` : ''}
          </div>
          <div style="padding:12px;">
            <h4 style="margin:0 0 8px 0;font-size:13px;color:#fff;font-weight:600;line-height:1.3;">\${ad.title}</h4>
            <div style="display:flex;align-items:center;justify-content:space-between;padding-top:8px;border-top:1px solid #262626;">
              <span style="color:#34d399;font-weight:bold;font-size:14px;">\${ad.sale_price || ad.reg_price || ''}</span>
              <a href="\${ad.target_url}" target="_blank" rel="noopener sponsored" style="background:#4f46e5;color:#fff;padding:6px 12px;border-radius:6px;font-size:11px;font-weight:600;text-decoration:none;">Shop Now</a>
            </div>
          </div>
        </div>
      \`;
    })
    .catch(err => console.debug('No sponsored fill available', err));
})();
</script>`;

  const reactSnippet = `import React, { useEffect, useState } from 'react';

export function SponsoredProductWidget({ format = 'square', category = 'global' }) {
  const [ad, setAd] = useState(null);

  useEffect(() => {
    // Queries edge CDN static distribution manifest
    fetch(\`https://cdn.sponsorgrid.net/manifests/\${category}/\${format}.json\`)
      .then(res => res.json())
      .then(data => setAd(data))
      .catch(() => setAd(null));
  }, [format, category]);

  if (!ad) return null;

  return (
    <aside className="w-[300px] bg-neutral-900 border border-neutral-800 rounded-xl overflow-hidden shadow-lg">
      <div className="relative h-32 bg-neutral-950">
        <img src={ad.image_url} alt={ad.title} className="w-full h-full object-cover" />
        <span className="absolute top-2 left-2 text-[9px] font-mono uppercase px-1.5 py-0.5 rounded bg-black/70 text-neutral-300">
          Sponsored
        </span>
        {ad.discount_badge && (
          <span className="absolute top-2 right-2 text-[10px] font-bold px-1.5 py-0.5 rounded bg-amber-500 text-black">
            {ad.discount_badge}
          </span>
        )}
      </div>
      <div className="p-3">
        <h4 className="text-xs font-semibold text-white line-clamp-2">{ad.title}</h4>
        <div className="flex items-center justify-between mt-3 pt-2 border-t border-neutral-800">
          <span className="text-emerald-400 font-bold font-mono text-sm">{ad.sale_price || ad.reg_price}</span>
          <a
            href={ad.target_url}
            target="_blank"
            rel="noopener sponsored"
            className="px-3 py-1 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-md transition-colors"
          >
            Claim Offer
          </a>
        </div>
      </div>
    </aside>
  );
}`;

  const compilerWorkerSnippet = `// Serverless Manifest Compiler (Webhook Consumer on Cloudflare Worker or AWS Lambda)
export default {
  async fetch(request, env) {
    if (request.method !== 'POST') return new Response('Method Not Allowed', { status: 405 });
    
    const body = await request.json();
    console.log('Received compiler rebuild event:', body.event, 'for record:', body.record?.title);
    
    // 1. Fetch latest active ads from Supabase sponsored_products
    const supabaseRes = await fetch(\`\${env.SUPABASE_URL}/rest/v1/sponsored_products?status=eq.active&order=created_at.desc\`, {
      headers: {
        'apikey': env.SUPABASE_ANON_KEY,
        'Authorization': \`Bearer \${env.SUPABASE_ANON_KEY}\`
      }
    });
    
    const activeAds = await supabaseRes.json();
    
    // 2. Recompile static JSON distribution files grouped by category & format
    // 3. Write directly to Edge CDN bucket / S3 storage (e.g. cdn.sponsorgrid.net)
    
    return new Response(JSON.stringify({
      success: true,
      compiledRecords: activeAds.length,
      timestamp: new Date().toISOString()
    }), {
      headers: { 'Content-Type': 'application/json' }
    });
  }
};`;

  const getCode = () => {
    switch (activeTab) {
      case 'sql':
        return sqlSchema;
      case 'vanilla':
        return vanillaJsEmbed;
      case 'react':
        return reactSnippet;
      case 'worker':
        return compilerWorkerSnippet;
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-neutral-800/80 border border-neutral-700/80 rounded-xl shadow-xl overflow-hidden">
        {/* Header */}
        <div className="px-6 py-4 border-b border-neutral-700/80 bg-neutral-800 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-base font-semibold text-white">Database Schema &amp; Developer Integration</h2>
            <p className="text-xs text-neutral-400 mt-0.5">
              Production DDL for Supabase PostgreSQL and client embed integrations
            </p>
          </div>

          <div className="flex items-center gap-2">
            <div className="flex items-center p-0.5 bg-neutral-900 rounded-lg border border-neutral-700">
              <button
                onClick={() => setActiveTab('sql')}
                className={`px-3 py-1 text-xs font-medium rounded-md transition-colors ${
                  activeTab === 'sql' ? 'bg-neutral-700 text-white' : 'text-neutral-400 hover:text-white'
                }`}
              >
                Supabase SQL
              </button>
              <button
                onClick={() => setActiveTab('vanilla')}
                className={`px-3 py-1 text-xs font-medium rounded-md transition-colors ${
                  activeTab === 'vanilla' ? 'bg-neutral-700 text-white' : 'text-neutral-400 hover:text-white'
                }`}
              >
                HTML Embed
              </button>
              <button
                onClick={() => setActiveTab('react')}
                className={`px-3 py-1 text-xs font-medium rounded-md transition-colors ${
                  activeTab === 'react' ? 'bg-neutral-700 text-white' : 'text-neutral-400 hover:text-white'
                }`}
              >
                React Component
              </button>
              <button
                onClick={() => setActiveTab('worker')}
                className={`px-3 py-1 text-xs font-medium rounded-md transition-colors ${
                  activeTab === 'worker' ? 'bg-neutral-700 text-white' : 'text-neutral-400 hover:text-white'
                }`}
              >
                Webhook Worker
              </button>
            </div>

            <button
              onClick={handleCopy}
              className="px-3 py-1 text-xs font-medium text-white bg-indigo-600 hover:bg-indigo-500 rounded-lg transition-colors flex items-center gap-1.5"
            >
              {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Code'}</span>
            </button>
          </div>
        </div>

        {/* Code View */}
        <div className="p-4 bg-neutral-950 font-mono text-xs text-neutral-300 overflow-x-auto max-h-[500px]">
          <pre className="leading-relaxed">
            <code>{getCode()}</code>
          </pre>
        </div>

        {/* Footer Explanations */}
        <div className="px-6 py-3 bg-neutral-900 border-t border-neutral-800 text-xs text-neutral-400 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>
              Includes RLS policies, indexing on <code className="text-neutral-300 font-mono">(status, format)</code>, and UUID primary keys.
            </span>
          </div>
          <span className="text-neutral-500 font-mono text-[11px]">
            Compatible with PostgreSQL 14+ / Supabase
          </span>
        </div>
      </div>
    </div>
  );
};
